[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

; 1. 憋住，按回车才发送整句
monitor_filters = send_on_enter
; 2. 开启本地回显，让你能看见自己敲了什么字！
monitor_echo = yes

lib_deps = 
    gin66/FastAccelStepper @ ^0.30.15